### ISSUE TITLE
Release of PhantomJS 2.1

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#12970]
- [x] Update ChangeLog
- [x] Update web sites
- [x] Create and update release notes
- [x] Update build instructions on the web site
- [ ] Prepare and upload source tarball (#13930)
- [x] Prepare OS X binary
- [x] Prepare Windows binary
- [x] Prepare Linux 64-bit binary (using Docker, see #13822)
- [x] Prepare Linux 32-bit binary (still problematic, see #13849)

**Comment by sochka** [comment]
Any approximation on release dates?

**Comment by sandstrom** [comment]
Somewhat unrelated, but may I suggest using an axe on the issues tracker :) There are tons of issues, many with insufficient information to be useful.

Being the main author I think it's easier for you to decide, but I think it would be useful to close most issues (e.g. with a note on it being reopened if additional information is added).

**Comment by madelson** [comment]
When will this be released? We are eagerly awaiting WOFF support

**Comment by LeMoussel** [comment]
I'm waiting of this release to test remote debugging capabilities on Windows 7.

**Comment by interactionist** [comment]
Same here. +1

**Comment by Vitallium** [comment]
Blocking issues from releasing 2.1 version:

- [ ] Upgrade Qt to 5.4.2
- [ ] Upgrade QtWebkit to 5.4.2

**Comment by mneumark** [comment]
It seems like based on the last activity in the `2.0.1` Issue, that release is dead and has been rolled into `2.1`. Is that true?

Asking because we are still awaiting support for Mac OS X 10.11 El Capitan. Any idea how far from release you are?

**Comment by dbrans** [comment]
+1

**Comment by ariya** [comment]
Current plan: let's try to have 2.1 release this month (January 2016).

**Comment by lkraav** [comment]
Not trying to offtopic this, but can I ask where is the funding for this project discussed or could an issue be created to talk about it? This project seems to have a massive community interest (including myself) and hypothesis is there's probably more people than just me who would be happy to back it with more than words.

**Comment by dcleao** [comment]
Yay!!

**Comment by ariya** [comment]
How I can help PhantomJS development? -> #13861

**Comment by zhagnsz** [comment]
@ariya It's cool, thank you!

**Comment by dcleao** [comment]
@ariya Great! Also looking forward to :-)

**Comment by mbrevda** [comment]
It seems there is an i686 package that was published. Does that mean 32-bit is ready?

**Comment by ariya** [comment]
To avoid confusion, please don't download/try/say anything about the release until I make the official announcement on the mailing-list. Your patience is appreciated!

**Comment by mbrevda** [comment]
:+1:

**Comment by ariya** [comment]
For now, we can't offer a source tarball (see #13930 for details). Thus, I'll just link to the git repo instead.

**Comment by ariya** [comment]
Announced! https://groups.google.com/d/msg/phantomjs/Jp4sDXrfmNg/I5J5TBFBDQAJ

**Comment by elachlan** [comment]
Thanks for your hard work Ariya and Team!

**Comment by ariya** [comment]
**Completed** :smile:

**Comment by EFF** [comment]
Yay! Thanks for the good work !

**Comment by felipebrahm** [comment]
@ariya is it expected for this binary not to work on CentOS 5? Using CentOS 5.9 I get this:

```
$ ldd ./phantomjs-2.1.1-linux-x86_64/bin/phantomjs 
./phantomjs-2.1.1-linux-x86_64/bin/phantomjs: /lib64/libc.so.6: version `GLIBC_2.9' not found (required by ./phantomjs-2.1.1-linux-x86_64/bin/phantomjs)
./phantomjs-2.1.1-linux-x86_64/bin/phantomjs: /lib64/libc.so.6: version `GLIBC_2.10' not found (required by ./phantomjs-2.1.1-linux-x86_64/bin/phantomjs)
./phantomjs-2.1.1-linux-x86_64/bin/phantomjs: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by ./phantomjs-2.1.1-linux-x86_64/bin/phantomjs)
	linux-vdso.so.1 =>  (0x00007fff81deb000)
	libz.so.1 => /usr/local/lib/libz.so.1 (0x00002b96941ed000)
	libfontconfig.so.1 => /usr/local/lib/libfontconfig.so.1 (0x00002b9694405000)
	libfreetype.so.6 => /usr/local/lib/libfreetype.so.6 (0x00002b9694645000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002b96948cd000)
	librt.so.1 => /lib64/librt.so.1 (0x00002b9694ad1000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b9694cdb000)
	libstdc++.so.6 => /usr/local/lib64/libstdc++.so.6 (0x00002b9694ef7000)
	libm.so.6 => /lib64/libm.so.6 (0x00002b96951fb000)
	libgcc_s.so.1 => /usr/local/lib64/libgcc_s.so.1 (0x00002b969547f000)
	libc.so.6 => /lib64/libc.so.6 (0x00002b9695694000)
	/lib64/ld-linux-x86-64.so.2 (0x00002b9693fcf000)
	libexpat.so.1 => /usr/local/lib/libexpat.so.1 (0x00002b96959ec000)
```
I tried searching this repo to see if support was removed on purpose but couldn't find any info about it. Thanks.

**Comment by ariya** [comment]
@felipebrahm Please file a new issue.

**Comment by jahtalab** [comment]
npm install on linux still tries to download a dead link:
https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2
the npm package needs to be updated?

**Comment by Sanjo** [comment]
@jahtalab Try this: `npm install -g phantomjs`. Works for me.

**Comment by ariya** [comment]
This issue is resolved because we achieved our goal: releasing 2.1.

If there is a problem with the release, please file a new issue. For anything npm-related, please bring it up at https://github.com/Medium/phantomjs.
