### ISSUE TITLE
WIP: test suite overhaul

### ISSUE THREAD

**Issue by zackw** [ariya/phantomjs#13478]
I have been overhauling the test suite on my branch [better-test-harness](https://github.com/zackw/phantomjs/commits/better-test-harness).  It's not done yet, but here is a list of the things I am trying to accomplish.  I may add more stuff to this later as I remember it.

- [x] A test harness (based on W3C [testharness.js](https://github.com/w3c/testharness.js)) that supports asynchrony.  This is essential to removing race conditions (leading to intermittent failures) from basically every test that loads a web page.
- [x] Convert existing tests to this test harness. (Some tests can't use the harness, e.g. those that test `phantom.exit` or `phantom.onError`.)
- [x] Eliminate all cases where the test suite depends on an external website.
- [x] Structured test output  ([TAP](https://testanything.org/)) which the test runner parses.
- [x] Mechanism for testing what gets output where (e.g. so we can test #10150).
- [x] Improvements to the Python test runner:
 - [x] Execute tests in alphabetical order.
 - [x] Support multi-level wildcards in `TESTS` array (needs to be edited even less often).
 - [x] Add ability to run a single test case (with the server available) under gdb.
 - [x] Better handling of HTTP server errors during a test.
 - [x] Better handling of many concurrent HTTP requests.
 - [x] HTTPS server (using a snakeoil certificate).
 - [x] Get rid of the hard-coded server ports.
 - [x] Misc code refactoring and cleanup.
- [x] Documentation.
- [ ] ~~Fold GhostDriver tests into the new world order~~ Deferred to #13515.
- [ ] ~~Tests for persistent state~~ Deferred to #13516.

**Comment by zackw** [comment]
This is now ready to be reviewed (in pull request #13517); a few originally-planned changes have been deferred to other bugs and I may or may not get to them soon.
